services:
  - type: web
    name: assigntrack
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: python -m gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: assigntrack-db
          property: connectionString
      - key: MEDIA_ROOT
        value: /var/data/media
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: assigntrack

databases:
  - name: assigntrack-db
